/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as LSlugRouteImport } from './routes/l.$slug'
import { Route as HooksMetaSyncRouteImport } from './routes/hooks.meta-sync'
import { Route as HooksMetaAssetFileRouteImport } from './routes/hooks.meta-asset-file'
import { Route as HooksHealthRouteImport } from './routes/hooks.health'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthAcceptInviteRouteImport } from './routes/auth.accept-invite'
import { Route as AppContaRouteImport } from './routes/app.conta'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as HooksTiktokOauthStartRouteImport } from './routes/hooks.tiktok-oauth.start'
import { Route as HooksTiktokOauthCallbackRouteImport } from './routes/hooks.tiktok-oauth.callback'
import { Route as HooksMetaOauthStartRouteImport } from './routes/hooks.meta-oauth.start'
import { Route as HooksMetaOauthCallbackRouteImport } from './routes/hooks.meta-oauth.callback'
import { Route as HooksHotmartWebhookRouteImport } from './routes/hooks.hotmart.webhook'
import { Route as HooksGoogleOauthStartRouteImport } from './routes/hooks.google-oauth.start'
import { Route as HooksGoogleOauthCallbackRouteImport } from './routes/hooks.google-oauth.callback'
import { Route as HooksAuthGoogleStartRouteImport } from './routes/hooks.auth-google.start'
import { Route as HooksAuthGoogleCallbackRouteImport } from './routes/hooks.auth-google.callback'
import { Route as AppProjectsProjectIdRouteImport } from './routes/app.projects.$projectId'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/app.projects.$projectId.index'
import { Route as AppAdminLandingsIndexRouteImport } from './routes/app.admin.landings.index'
import { Route as AppProjectsProjectIdPaidRouteImport } from './routes/app.projects.$projectId.paid'
import { Route as AppAdminLandingsLandingIdRouteImport } from './routes/app.admin.landings.$landingId'
import { Route as AppProjectsProjectIdPaidIndexRouteImport } from './routes/app.projects.$projectId.paid.index'
import { Route as AppProjectsProjectIdLandingsIndexRouteImport } from './routes/app.projects.$projectId.landings.index'
import { Route as AppProjectsProjectIdPaidTiktokRouteImport } from './routes/app.projects.$projectId.paid.tiktok'
import { Route as AppProjectsProjectIdPaidMetaRouteImport } from './routes/app.projects.$projectId.paid.meta'
import { Route as AppProjectsProjectIdPaidAuditRouteImport } from './routes/app.projects.$projectId.paid.audit'
import { Route as AppProjectsProjectIdPaidApprovalsRouteImport } from './routes/app.projects.$projectId.paid.approvals'
import { Route as AppProjectsProjectIdOrganizationMembersRouteImport } from './routes/app.projects.$projectId.organization.members'
import { Route as AppProjectsProjectIdLandingsLandingIdRouteImport } from './routes/app.projects.$projectId.landings.$landingId'
import { Route as AppProjectsProjectIdPaidTiktokIndexRouteImport } from './routes/app.projects.$projectId.paid.tiktok.index'
import { Route as AppProjectsProjectIdPaidMetaIndexRouteImport } from './routes/app.projects.$projectId.paid.meta.index'
import { Route as AppProjectsProjectIdPaidCampaignsIndexRouteImport } from './routes/app.projects.$projectId.paid.campaigns.index'
import { Route as AppProjectsProjectIdPaidTiktokCampaignsRouteImport } from './routes/app.projects.$projectId.paid.tiktok.campaigns'
import { Route as AppProjectsProjectIdPaidMetaWizardRouteImport } from './routes/app.projects.$projectId.paid.meta.wizard'
import { Route as AppProjectsProjectIdPaidMetaCampaignsRouteImport } from './routes/app.projects.$projectId.paid.meta.campaigns'
import { Route as AppProjectsProjectIdPaidCampaignsNewRouteImport } from './routes/app.projects.$projectId.paid.campaigns.new'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const LSlugRoute = LSlugRouteImport.update({
  id: '/l/$slug',
  path: '/l/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksMetaSyncRoute = HooksMetaSyncRouteImport.update({
  id: '/hooks/meta-sync',
  path: '/hooks/meta-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksMetaAssetFileRoute = HooksMetaAssetFileRouteImport.update({
  id: '/hooks/meta-asset-file',
  path: '/hooks/meta-asset-file',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksHealthRoute = HooksHealthRouteImport.update({
  id: '/hooks/health',
  path: '/hooks/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAcceptInviteRoute = AuthAcceptInviteRouteImport.update({
  id: '/auth/accept-invite',
  path: '/auth/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AppContaRoute = AppContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const HooksTiktokOauthStartRoute = HooksTiktokOauthStartRouteImport.update({
  id: '/hooks/tiktok-oauth/start',
  path: '/hooks/tiktok-oauth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksTiktokOauthCallbackRoute =
  HooksTiktokOauthCallbackRouteImport.update({
    id: '/hooks/tiktok-oauth/callback',
    path: '/hooks/tiktok-oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksMetaOauthStartRoute = HooksMetaOauthStartRouteImport.update({
  id: '/hooks/meta-oauth/start',
  path: '/hooks/meta-oauth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksMetaOauthCallbackRoute = HooksMetaOauthCallbackRouteImport.update({
  id: '/hooks/meta-oauth/callback',
  path: '/hooks/meta-oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksHotmartWebhookRoute = HooksHotmartWebhookRouteImport.update({
  id: '/hooks/hotmart/webhook',
  path: '/hooks/hotmart/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksGoogleOauthStartRoute = HooksGoogleOauthStartRouteImport.update({
  id: '/hooks/google-oauth/start',
  path: '/hooks/google-oauth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksGoogleOauthCallbackRoute =
  HooksGoogleOauthCallbackRouteImport.update({
    id: '/hooks/google-oauth/callback',
    path: '/hooks/google-oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksAuthGoogleStartRoute = HooksAuthGoogleStartRouteImport.update({
  id: '/hooks/auth-google/start',
  path: '/hooks/auth-google/start',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksAuthGoogleCallbackRoute = HooksAuthGoogleCallbackRouteImport.update({
  id: '/hooks/auth-google/callback',
  path: '/hooks/auth-google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppAdminLandingsIndexRoute = AppAdminLandingsIndexRouteImport.update({
  id: '/landings/',
  path: '/landings/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppProjectsProjectIdPaidRoute =
  AppProjectsProjectIdPaidRouteImport.update({
    id: '/paid',
    path: '/paid',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppAdminLandingsLandingIdRoute =
  AppAdminLandingsLandingIdRouteImport.update({
    id: '/landings/$landingId',
    path: '/landings/$landingId',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppProjectsProjectIdPaidIndexRoute =
  AppProjectsProjectIdPaidIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdPaidRoute,
  } as any)
const AppProjectsProjectIdLandingsIndexRoute =
  AppProjectsProjectIdLandingsIndexRouteImport.update({
    id: '/landings/',
    path: '/landings/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdPaidTiktokRoute =
  AppProjectsProjectIdPaidTiktokRouteImport.update({
    id: '/tiktok',
    path: '/tiktok',
    getParentRoute: () => AppProjectsProjectIdPaidRoute,
  } as any)
const AppProjectsProjectIdPaidMetaRoute =
  AppProjectsProjectIdPaidMetaRouteImport.update({
    id: '/meta',
    path: '/meta',
    getParentRoute: () => AppProjectsProjectIdPaidRoute,
  } as any)
const AppProjectsProjectIdPaidAuditRoute =
  AppProjectsProjectIdPaidAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AppProjectsProjectIdPaidRoute,
  } as any)
const AppProjectsProjectIdPaidApprovalsRoute =
  AppProjectsProjectIdPaidApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AppProjectsProjectIdPaidRoute,
  } as any)
const AppProjectsProjectIdOrganizationMembersRoute =
  AppProjectsProjectIdOrganizationMembersRouteImport.update({
    id: '/organization/members',
    path: '/organization/members',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdLandingsLandingIdRoute =
  AppProjectsProjectIdLandingsLandingIdRouteImport.update({
    id: '/landings/$landingId',
    path: '/landings/$landingId',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdPaidTiktokIndexRoute =
  AppProjectsProjectIdPaidTiktokIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdPaidTiktokRoute,
  } as any)
const AppProjectsProjectIdPaidMetaIndexRoute =
  AppProjectsProjectIdPaidMetaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdPaidMetaRoute,
  } as any)
const AppProjectsProjectIdPaidCampaignsIndexRoute =
  AppProjectsProjectIdPaidCampaignsIndexRouteImport.update({
    id: '/campaigns/',
    path: '/campaigns/',
    getParentRoute: () => AppProjectsProjectIdPaidRoute,
  } as any)
const AppProjectsProjectIdPaidTiktokCampaignsRoute =
  AppProjectsProjectIdPaidTiktokCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AppProjectsProjectIdPaidTiktokRoute,
  } as any)
const AppProjectsProjectIdPaidMetaWizardRoute =
  AppProjectsProjectIdPaidMetaWizardRouteImport.update({
    id: '/wizard',
    path: '/wizard',
    getParentRoute: () => AppProjectsProjectIdPaidMetaRoute,
  } as any)
const AppProjectsProjectIdPaidMetaCampaignsRoute =
  AppProjectsProjectIdPaidMetaCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AppProjectsProjectIdPaidMetaRoute,
  } as any)
const AppProjectsProjectIdPaidCampaignsNewRoute =
  AppProjectsProjectIdPaidCampaignsNewRouteImport.update({
    id: '/campaigns/new',
    path: '/campaigns/new',
    getParentRoute: () => AppProjectsProjectIdPaidRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/conta': typeof AppContaRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/hooks/health': typeof HooksHealthRoute
  '/hooks/meta-asset-file': typeof HooksMetaAssetFileRoute
  '/hooks/meta-sync': typeof HooksMetaSyncRoute
  '/l/$slug': typeof LSlugRoute
  '/app/': typeof AppIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/hooks/auth-google/callback': typeof HooksAuthGoogleCallbackRoute
  '/hooks/auth-google/start': typeof HooksAuthGoogleStartRoute
  '/hooks/google-oauth/callback': typeof HooksGoogleOauthCallbackRoute
  '/hooks/google-oauth/start': typeof HooksGoogleOauthStartRoute
  '/hooks/hotmart/webhook': typeof HooksHotmartWebhookRoute
  '/hooks/meta-oauth/callback': typeof HooksMetaOauthCallbackRoute
  '/hooks/meta-oauth/start': typeof HooksMetaOauthStartRoute
  '/hooks/tiktok-oauth/callback': typeof HooksTiktokOauthCallbackRoute
  '/hooks/tiktok-oauth/start': typeof HooksTiktokOauthStartRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/admin/landings/$landingId': typeof AppAdminLandingsLandingIdRoute
  '/app/projects/$projectId/paid': typeof AppProjectsProjectIdPaidRouteWithChildren
  '/app/admin/landings/': typeof AppAdminLandingsIndexRoute
  '/app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/app/projects/$projectId/landings/$landingId': typeof AppProjectsProjectIdLandingsLandingIdRoute
  '/app/projects/$projectId/organization/members': typeof AppProjectsProjectIdOrganizationMembersRoute
  '/app/projects/$projectId/paid/approvals': typeof AppProjectsProjectIdPaidApprovalsRoute
  '/app/projects/$projectId/paid/audit': typeof AppProjectsProjectIdPaidAuditRoute
  '/app/projects/$projectId/paid/meta': typeof AppProjectsProjectIdPaidMetaRouteWithChildren
  '/app/projects/$projectId/paid/tiktok': typeof AppProjectsProjectIdPaidTiktokRouteWithChildren
  '/app/projects/$projectId/landings/': typeof AppProjectsProjectIdLandingsIndexRoute
  '/app/projects/$projectId/paid/': typeof AppProjectsProjectIdPaidIndexRoute
  '/app/projects/$projectId/paid/campaigns/new': typeof AppProjectsProjectIdPaidCampaignsNewRoute
  '/app/projects/$projectId/paid/meta/campaigns': typeof AppProjectsProjectIdPaidMetaCampaignsRoute
  '/app/projects/$projectId/paid/meta/wizard': typeof AppProjectsProjectIdPaidMetaWizardRoute
  '/app/projects/$projectId/paid/tiktok/campaigns': typeof AppProjectsProjectIdPaidTiktokCampaignsRoute
  '/app/projects/$projectId/paid/campaigns/': typeof AppProjectsProjectIdPaidCampaignsIndexRoute
  '/app/projects/$projectId/paid/meta/': typeof AppProjectsProjectIdPaidMetaIndexRoute
  '/app/projects/$projectId/paid/tiktok/': typeof AppProjectsProjectIdPaidTiktokIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/conta': typeof AppContaRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/hooks/health': typeof HooksHealthRoute
  '/hooks/meta-asset-file': typeof HooksMetaAssetFileRoute
  '/hooks/meta-sync': typeof HooksMetaSyncRoute
  '/l/$slug': typeof LSlugRoute
  '/app': typeof AppIndexRoute
  '/hooks/auth-google/callback': typeof HooksAuthGoogleCallbackRoute
  '/hooks/auth-google/start': typeof HooksAuthGoogleStartRoute
  '/hooks/google-oauth/callback': typeof HooksGoogleOauthCallbackRoute
  '/hooks/google-oauth/start': typeof HooksGoogleOauthStartRoute
  '/hooks/hotmart/webhook': typeof HooksHotmartWebhookRoute
  '/hooks/meta-oauth/callback': typeof HooksMetaOauthCallbackRoute
  '/hooks/meta-oauth/start': typeof HooksMetaOauthStartRoute
  '/hooks/tiktok-oauth/callback': typeof HooksTiktokOauthCallbackRoute
  '/hooks/tiktok-oauth/start': typeof HooksTiktokOauthStartRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/admin/landings/$landingId': typeof AppAdminLandingsLandingIdRoute
  '/app/admin/landings': typeof AppAdminLandingsIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
  '/app/projects/$projectId/landings/$landingId': typeof AppProjectsProjectIdLandingsLandingIdRoute
  '/app/projects/$projectId/organization/members': typeof AppProjectsProjectIdOrganizationMembersRoute
  '/app/projects/$projectId/paid/approvals': typeof AppProjectsProjectIdPaidApprovalsRoute
  '/app/projects/$projectId/paid/audit': typeof AppProjectsProjectIdPaidAuditRoute
  '/app/projects/$projectId/landings': typeof AppProjectsProjectIdLandingsIndexRoute
  '/app/projects/$projectId/paid': typeof AppProjectsProjectIdPaidIndexRoute
  '/app/projects/$projectId/paid/campaigns/new': typeof AppProjectsProjectIdPaidCampaignsNewRoute
  '/app/projects/$projectId/paid/meta/campaigns': typeof AppProjectsProjectIdPaidMetaCampaignsRoute
  '/app/projects/$projectId/paid/meta/wizard': typeof AppProjectsProjectIdPaidMetaWizardRoute
  '/app/projects/$projectId/paid/tiktok/campaigns': typeof AppProjectsProjectIdPaidTiktokCampaignsRoute
  '/app/projects/$projectId/paid/campaigns': typeof AppProjectsProjectIdPaidCampaignsIndexRoute
  '/app/projects/$projectId/paid/meta': typeof AppProjectsProjectIdPaidMetaIndexRoute
  '/app/projects/$projectId/paid/tiktok': typeof AppProjectsProjectIdPaidTiktokIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/conta': typeof AppContaRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/hooks/health': typeof HooksHealthRoute
  '/hooks/meta-asset-file': typeof HooksMetaAssetFileRoute
  '/hooks/meta-sync': typeof HooksMetaSyncRoute
  '/l/$slug': typeof LSlugRoute
  '/app/': typeof AppIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/hooks/auth-google/callback': typeof HooksAuthGoogleCallbackRoute
  '/hooks/auth-google/start': typeof HooksAuthGoogleStartRoute
  '/hooks/google-oauth/callback': typeof HooksGoogleOauthCallbackRoute
  '/hooks/google-oauth/start': typeof HooksGoogleOauthStartRoute
  '/hooks/hotmart/webhook': typeof HooksHotmartWebhookRoute
  '/hooks/meta-oauth/callback': typeof HooksMetaOauthCallbackRoute
  '/hooks/meta-oauth/start': typeof HooksMetaOauthStartRoute
  '/hooks/tiktok-oauth/callback': typeof HooksTiktokOauthCallbackRoute
  '/hooks/tiktok-oauth/start': typeof HooksTiktokOauthStartRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/admin/landings/$landingId': typeof AppAdminLandingsLandingIdRoute
  '/app/projects/$projectId/paid': typeof AppProjectsProjectIdPaidRouteWithChildren
  '/app/admin/landings/': typeof AppAdminLandingsIndexRoute
  '/app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/app/projects/$projectId/landings/$landingId': typeof AppProjectsProjectIdLandingsLandingIdRoute
  '/app/projects/$projectId/organization/members': typeof AppProjectsProjectIdOrganizationMembersRoute
  '/app/projects/$projectId/paid/approvals': typeof AppProjectsProjectIdPaidApprovalsRoute
  '/app/projects/$projectId/paid/audit': typeof AppProjectsProjectIdPaidAuditRoute
  '/app/projects/$projectId/paid/meta': typeof AppProjectsProjectIdPaidMetaRouteWithChildren
  '/app/projects/$projectId/paid/tiktok': typeof AppProjectsProjectIdPaidTiktokRouteWithChildren
  '/app/projects/$projectId/landings/': typeof AppProjectsProjectIdLandingsIndexRoute
  '/app/projects/$projectId/paid/': typeof AppProjectsProjectIdPaidIndexRoute
  '/app/projects/$projectId/paid/campaigns/new': typeof AppProjectsProjectIdPaidCampaignsNewRoute
  '/app/projects/$projectId/paid/meta/campaigns': typeof AppProjectsProjectIdPaidMetaCampaignsRoute
  '/app/projects/$projectId/paid/meta/wizard': typeof AppProjectsProjectIdPaidMetaWizardRoute
  '/app/projects/$projectId/paid/tiktok/campaigns': typeof AppProjectsProjectIdPaidTiktokCampaignsRoute
  '/app/projects/$projectId/paid/campaigns/': typeof AppProjectsProjectIdPaidCampaignsIndexRoute
  '/app/projects/$projectId/paid/meta/': typeof AppProjectsProjectIdPaidMetaIndexRoute
  '/app/projects/$projectId/paid/tiktok/': typeof AppProjectsProjectIdPaidTiktokIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/conta'
    | '/auth/accept-invite'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/hooks/health'
    | '/hooks/meta-asset-file'
    | '/hooks/meta-sync'
    | '/l/$slug'
    | '/app/'
    | '/app/projects/$projectId'
    | '/hooks/auth-google/callback'
    | '/hooks/auth-google/start'
    | '/hooks/google-oauth/callback'
    | '/hooks/google-oauth/start'
    | '/hooks/hotmart/webhook'
    | '/hooks/meta-oauth/callback'
    | '/hooks/meta-oauth/start'
    | '/hooks/tiktok-oauth/callback'
    | '/hooks/tiktok-oauth/start'
    | '/app/admin/'
    | '/app/admin/landings/$landingId'
    | '/app/projects/$projectId/paid'
    | '/app/admin/landings/'
    | '/app/projects/$projectId/'
    | '/app/projects/$projectId/landings/$landingId'
    | '/app/projects/$projectId/organization/members'
    | '/app/projects/$projectId/paid/approvals'
    | '/app/projects/$projectId/paid/audit'
    | '/app/projects/$projectId/paid/meta'
    | '/app/projects/$projectId/paid/tiktok'
    | '/app/projects/$projectId/landings/'
    | '/app/projects/$projectId/paid/'
    | '/app/projects/$projectId/paid/campaigns/new'
    | '/app/projects/$projectId/paid/meta/campaigns'
    | '/app/projects/$projectId/paid/meta/wizard'
    | '/app/projects/$projectId/paid/tiktok/campaigns'
    | '/app/projects/$projectId/paid/campaigns/'
    | '/app/projects/$projectId/paid/meta/'
    | '/app/projects/$projectId/paid/tiktok/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/conta'
    | '/auth/accept-invite'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/hooks/health'
    | '/hooks/meta-asset-file'
    | '/hooks/meta-sync'
    | '/l/$slug'
    | '/app'
    | '/hooks/auth-google/callback'
    | '/hooks/auth-google/start'
    | '/hooks/google-oauth/callback'
    | '/hooks/google-oauth/start'
    | '/hooks/hotmart/webhook'
    | '/hooks/meta-oauth/callback'
    | '/hooks/meta-oauth/start'
    | '/hooks/tiktok-oauth/callback'
    | '/hooks/tiktok-oauth/start'
    | '/app/admin'
    | '/app/admin/landings/$landingId'
    | '/app/admin/landings'
    | '/app/projects/$projectId'
    | '/app/projects/$projectId/landings/$landingId'
    | '/app/projects/$projectId/organization/members'
    | '/app/projects/$projectId/paid/approvals'
    | '/app/projects/$projectId/paid/audit'
    | '/app/projects/$projectId/landings'
    | '/app/projects/$projectId/paid'
    | '/app/projects/$projectId/paid/campaigns/new'
    | '/app/projects/$projectId/paid/meta/campaigns'
    | '/app/projects/$projectId/paid/meta/wizard'
    | '/app/projects/$projectId/paid/tiktok/campaigns'
    | '/app/projects/$projectId/paid/campaigns'
    | '/app/projects/$projectId/paid/meta'
    | '/app/projects/$projectId/paid/tiktok'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/conta'
    | '/auth/accept-invite'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/hooks/health'
    | '/hooks/meta-asset-file'
    | '/hooks/meta-sync'
    | '/l/$slug'
    | '/app/'
    | '/app/projects/$projectId'
    | '/hooks/auth-google/callback'
    | '/hooks/auth-google/start'
    | '/hooks/google-oauth/callback'
    | '/hooks/google-oauth/start'
    | '/hooks/hotmart/webhook'
    | '/hooks/meta-oauth/callback'
    | '/hooks/meta-oauth/start'
    | '/hooks/tiktok-oauth/callback'
    | '/hooks/tiktok-oauth/start'
    | '/app/admin/'
    | '/app/admin/landings/$landingId'
    | '/app/projects/$projectId/paid'
    | '/app/admin/landings/'
    | '/app/projects/$projectId/'
    | '/app/projects/$projectId/landings/$landingId'
    | '/app/projects/$projectId/organization/members'
    | '/app/projects/$projectId/paid/approvals'
    | '/app/projects/$projectId/paid/audit'
    | '/app/projects/$projectId/paid/meta'
    | '/app/projects/$projectId/paid/tiktok'
    | '/app/projects/$projectId/landings/'
    | '/app/projects/$projectId/paid/'
    | '/app/projects/$projectId/paid/campaigns/new'
    | '/app/projects/$projectId/paid/meta/campaigns'
    | '/app/projects/$projectId/paid/meta/wizard'
    | '/app/projects/$projectId/paid/tiktok/campaigns'
    | '/app/projects/$projectId/paid/campaigns/'
    | '/app/projects/$projectId/paid/meta/'
    | '/app/projects/$projectId/paid/tiktok/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthAcceptInviteRoute: typeof AuthAcceptInviteRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  HooksHealthRoute: typeof HooksHealthRoute
  HooksMetaAssetFileRoute: typeof HooksMetaAssetFileRoute
  HooksMetaSyncRoute: typeof HooksMetaSyncRoute
  LSlugRoute: typeof LSlugRoute
  HooksAuthGoogleCallbackRoute: typeof HooksAuthGoogleCallbackRoute
  HooksAuthGoogleStartRoute: typeof HooksAuthGoogleStartRoute
  HooksGoogleOauthCallbackRoute: typeof HooksGoogleOauthCallbackRoute
  HooksGoogleOauthStartRoute: typeof HooksGoogleOauthStartRoute
  HooksHotmartWebhookRoute: typeof HooksHotmartWebhookRoute
  HooksMetaOauthCallbackRoute: typeof HooksMetaOauthCallbackRoute
  HooksMetaOauthStartRoute: typeof HooksMetaOauthStartRoute
  HooksTiktokOauthCallbackRoute: typeof HooksTiktokOauthCallbackRoute
  HooksTiktokOauthStartRoute: typeof HooksTiktokOauthStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/l/$slug': {
      id: '/l/$slug'
      path: '/l/$slug'
      fullPath: '/l/$slug'
      preLoaderRoute: typeof LSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/meta-sync': {
      id: '/hooks/meta-sync'
      path: '/hooks/meta-sync'
      fullPath: '/hooks/meta-sync'
      preLoaderRoute: typeof HooksMetaSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/meta-asset-file': {
      id: '/hooks/meta-asset-file'
      path: '/hooks/meta-asset-file'
      fullPath: '/hooks/meta-asset-file'
      preLoaderRoute: typeof HooksMetaAssetFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/health': {
      id: '/hooks/health'
      path: '/hooks/health'
      fullPath: '/hooks/health'
      preLoaderRoute: typeof HooksHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/accept-invite': {
      id: '/auth/accept-invite'
      path: '/auth/accept-invite'
      fullPath: '/auth/accept-invite'
      preLoaderRoute: typeof AuthAcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/conta': {
      id: '/app/conta'
      path: '/conta'
      fullPath: '/app/conta'
      preLoaderRoute: typeof AppContaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/hooks/tiktok-oauth/start': {
      id: '/hooks/tiktok-oauth/start'
      path: '/hooks/tiktok-oauth/start'
      fullPath: '/hooks/tiktok-oauth/start'
      preLoaderRoute: typeof HooksTiktokOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/tiktok-oauth/callback': {
      id: '/hooks/tiktok-oauth/callback'
      path: '/hooks/tiktok-oauth/callback'
      fullPath: '/hooks/tiktok-oauth/callback'
      preLoaderRoute: typeof HooksTiktokOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/meta-oauth/start': {
      id: '/hooks/meta-oauth/start'
      path: '/hooks/meta-oauth/start'
      fullPath: '/hooks/meta-oauth/start'
      preLoaderRoute: typeof HooksMetaOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/meta-oauth/callback': {
      id: '/hooks/meta-oauth/callback'
      path: '/hooks/meta-oauth/callback'
      fullPath: '/hooks/meta-oauth/callback'
      preLoaderRoute: typeof HooksMetaOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/hotmart/webhook': {
      id: '/hooks/hotmart/webhook'
      path: '/hooks/hotmart/webhook'
      fullPath: '/hooks/hotmart/webhook'
      preLoaderRoute: typeof HooksHotmartWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/google-oauth/start': {
      id: '/hooks/google-oauth/start'
      path: '/hooks/google-oauth/start'
      fullPath: '/hooks/google-oauth/start'
      preLoaderRoute: typeof HooksGoogleOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/google-oauth/callback': {
      id: '/hooks/google-oauth/callback'
      path: '/hooks/google-oauth/callback'
      fullPath: '/hooks/google-oauth/callback'
      preLoaderRoute: typeof HooksGoogleOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/auth-google/start': {
      id: '/hooks/auth-google/start'
      path: '/hooks/auth-google/start'
      fullPath: '/hooks/auth-google/start'
      preLoaderRoute: typeof HooksAuthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/auth-google/callback': {
      id: '/hooks/auth-google/callback'
      path: '/hooks/auth-google/callback'
      fullPath: '/hooks/auth-google/callback'
      preLoaderRoute: typeof HooksAuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$projectId/': {
      id: '/app/projects/$projectId/'
      path: '/'
      fullPath: '/app/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/admin/landings/': {
      id: '/app/admin/landings/'
      path: '/landings'
      fullPath: '/app/admin/landings/'
      preLoaderRoute: typeof AppAdminLandingsIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/projects/$projectId/paid': {
      id: '/app/projects/$projectId/paid'
      path: '/paid'
      fullPath: '/app/projects/$projectId/paid'
      preLoaderRoute: typeof AppProjectsProjectIdPaidRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/admin/landings/$landingId': {
      id: '/app/admin/landings/$landingId'
      path: '/landings/$landingId'
      fullPath: '/app/admin/landings/$landingId'
      preLoaderRoute: typeof AppAdminLandingsLandingIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/projects/$projectId/paid/': {
      id: '/app/projects/$projectId/paid/'
      path: '/'
      fullPath: '/app/projects/$projectId/paid/'
      preLoaderRoute: typeof AppProjectsProjectIdPaidIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdPaidRoute
    }
    '/app/projects/$projectId/landings/': {
      id: '/app/projects/$projectId/landings/'
      path: '/landings'
      fullPath: '/app/projects/$projectId/landings/'
      preLoaderRoute: typeof AppProjectsProjectIdLandingsIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/projects/$projectId/paid/tiktok': {
      id: '/app/projects/$projectId/paid/tiktok'
      path: '/tiktok'
      fullPath: '/app/projects/$projectId/paid/tiktok'
      preLoaderRoute: typeof AppProjectsProjectIdPaidTiktokRouteImport
      parentRoute: typeof AppProjectsProjectIdPaidRoute
    }
    '/app/projects/$projectId/paid/meta': {
      id: '/app/projects/$projectId/paid/meta'
      path: '/meta'
      fullPath: '/app/projects/$projectId/paid/meta'
      preLoaderRoute: typeof AppProjectsProjectIdPaidMetaRouteImport
      parentRoute: typeof AppProjectsProjectIdPaidRoute
    }
    '/app/projects/$projectId/paid/audit': {
      id: '/app/projects/$projectId/paid/audit'
      path: '/audit'
      fullPath: '/app/projects/$projectId/paid/audit'
      preLoaderRoute: typeof AppProjectsProjectIdPaidAuditRouteImport
      parentRoute: typeof AppProjectsProjectIdPaidRoute
    }
    '/app/projects/$projectId/paid/approvals': {
      id: '/app/projects/$projectId/paid/approvals'
      path: '/approvals'
      fullPath: '/app/projects/$projectId/paid/approvals'
      preLoaderRoute: typeof AppProjectsProjectIdPaidApprovalsRouteImport
      parentRoute: typeof AppProjectsProjectIdPaidRoute
    }
    '/app/projects/$projectId/organization/members': {
      id: '/app/projects/$projectId/organization/members'
      path: '/organization/members'
      fullPath: '/app/projects/$projectId/organization/members'
      preLoaderRoute: typeof AppProjectsProjectIdOrganizationMembersRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/projects/$projectId/landings/$landingId': {
      id: '/app/projects/$projectId/landings/$landingId'
      path: '/landings/$landingId'
      fullPath: '/app/projects/$projectId/landings/$landingId'
      preLoaderRoute: typeof AppProjectsProjectIdLandingsLandingIdRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/projects/$projectId/paid/tiktok/': {
      id: '/app/projects/$projectId/paid/tiktok/'
      path: '/'
      fullPath: '/app/projects/$projectId/paid/tiktok/'
      preLoaderRoute: typeof AppProjectsProjectIdPaidTiktokIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdPaidTiktokRoute
    }
    '/app/projects/$projectId/paid/meta/': {
      id: '/app/projects/$projectId/paid/meta/'
      path: '/'
      fullPath: '/app/projects/$projectId/paid/meta/'
      preLoaderRoute: typeof AppProjectsProjectIdPaidMetaIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdPaidMetaRoute
    }
    '/app/projects/$projectId/paid/campaigns/': {
      id: '/app/projects/$projectId/paid/campaigns/'
      path: '/campaigns'
      fullPath: '/app/projects/$projectId/paid/campaigns/'
      preLoaderRoute: typeof AppProjectsProjectIdPaidCampaignsIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdPaidRoute
    }
    '/app/projects/$projectId/paid/tiktok/campaigns': {
      id: '/app/projects/$projectId/paid/tiktok/campaigns'
      path: '/campaigns'
      fullPath: '/app/projects/$projectId/paid/tiktok/campaigns'
      preLoaderRoute: typeof AppProjectsProjectIdPaidTiktokCampaignsRouteImport
      parentRoute: typeof AppProjectsProjectIdPaidTiktokRoute
    }
    '/app/projects/$projectId/paid/meta/wizard': {
      id: '/app/projects/$projectId/paid/meta/wizard'
      path: '/wizard'
      fullPath: '/app/projects/$projectId/paid/meta/wizard'
      preLoaderRoute: typeof AppProjectsProjectIdPaidMetaWizardRouteImport
      parentRoute: typeof AppProjectsProjectIdPaidMetaRoute
    }
    '/app/projects/$projectId/paid/meta/campaigns': {
      id: '/app/projects/$projectId/paid/meta/campaigns'
      path: '/campaigns'
      fullPath: '/app/projects/$projectId/paid/meta/campaigns'
      preLoaderRoute: typeof AppProjectsProjectIdPaidMetaCampaignsRouteImport
      parentRoute: typeof AppProjectsProjectIdPaidMetaRoute
    }
    '/app/projects/$projectId/paid/campaigns/new': {
      id: '/app/projects/$projectId/paid/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/app/projects/$projectId/paid/campaigns/new'
      preLoaderRoute: typeof AppProjectsProjectIdPaidCampaignsNewRouteImport
      parentRoute: typeof AppProjectsProjectIdPaidRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminLandingsLandingIdRoute: typeof AppAdminLandingsLandingIdRoute
  AppAdminLandingsIndexRoute: typeof AppAdminLandingsIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminLandingsLandingIdRoute: AppAdminLandingsLandingIdRoute,
  AppAdminLandingsIndexRoute: AppAdminLandingsIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppProjectsProjectIdPaidMetaRouteChildren {
  AppProjectsProjectIdPaidMetaCampaignsRoute: typeof AppProjectsProjectIdPaidMetaCampaignsRoute
  AppProjectsProjectIdPaidMetaWizardRoute: typeof AppProjectsProjectIdPaidMetaWizardRoute
  AppProjectsProjectIdPaidMetaIndexRoute: typeof AppProjectsProjectIdPaidMetaIndexRoute
}

const AppProjectsProjectIdPaidMetaRouteChildren: AppProjectsProjectIdPaidMetaRouteChildren =
  {
    AppProjectsProjectIdPaidMetaCampaignsRoute:
      AppProjectsProjectIdPaidMetaCampaignsRoute,
    AppProjectsProjectIdPaidMetaWizardRoute:
      AppProjectsProjectIdPaidMetaWizardRoute,
    AppProjectsProjectIdPaidMetaIndexRoute:
      AppProjectsProjectIdPaidMetaIndexRoute,
  }

const AppProjectsProjectIdPaidMetaRouteWithChildren =
  AppProjectsProjectIdPaidMetaRoute._addFileChildren(
    AppProjectsProjectIdPaidMetaRouteChildren,
  )

interface AppProjectsProjectIdPaidTiktokRouteChildren {
  AppProjectsProjectIdPaidTiktokCampaignsRoute: typeof AppProjectsProjectIdPaidTiktokCampaignsRoute
  AppProjectsProjectIdPaidTiktokIndexRoute: typeof AppProjectsProjectIdPaidTiktokIndexRoute
}

const AppProjectsProjectIdPaidTiktokRouteChildren: AppProjectsProjectIdPaidTiktokRouteChildren =
  {
    AppProjectsProjectIdPaidTiktokCampaignsRoute:
      AppProjectsProjectIdPaidTiktokCampaignsRoute,
    AppProjectsProjectIdPaidTiktokIndexRoute:
      AppProjectsProjectIdPaidTiktokIndexRoute,
  }

const AppProjectsProjectIdPaidTiktokRouteWithChildren =
  AppProjectsProjectIdPaidTiktokRoute._addFileChildren(
    AppProjectsProjectIdPaidTiktokRouteChildren,
  )

interface AppProjectsProjectIdPaidRouteChildren {
  AppProjectsProjectIdPaidApprovalsRoute: typeof AppProjectsProjectIdPaidApprovalsRoute
  AppProjectsProjectIdPaidAuditRoute: typeof AppProjectsProjectIdPaidAuditRoute
  AppProjectsProjectIdPaidMetaRoute: typeof AppProjectsProjectIdPaidMetaRouteWithChildren
  AppProjectsProjectIdPaidTiktokRoute: typeof AppProjectsProjectIdPaidTiktokRouteWithChildren
  AppProjectsProjectIdPaidIndexRoute: typeof AppProjectsProjectIdPaidIndexRoute
  AppProjectsProjectIdPaidCampaignsNewRoute: typeof AppProjectsProjectIdPaidCampaignsNewRoute
  AppProjectsProjectIdPaidCampaignsIndexRoute: typeof AppProjectsProjectIdPaidCampaignsIndexRoute
}

const AppProjectsProjectIdPaidRouteChildren: AppProjectsProjectIdPaidRouteChildren =
  {
    AppProjectsProjectIdPaidApprovalsRoute:
      AppProjectsProjectIdPaidApprovalsRoute,
    AppProjectsProjectIdPaidAuditRoute: AppProjectsProjectIdPaidAuditRoute,
    AppProjectsProjectIdPaidMetaRoute:
      AppProjectsProjectIdPaidMetaRouteWithChildren,
    AppProjectsProjectIdPaidTiktokRoute:
      AppProjectsProjectIdPaidTiktokRouteWithChildren,
    AppProjectsProjectIdPaidIndexRoute: AppProjectsProjectIdPaidIndexRoute,
    AppProjectsProjectIdPaidCampaignsNewRoute:
      AppProjectsProjectIdPaidCampaignsNewRoute,
    AppProjectsProjectIdPaidCampaignsIndexRoute:
      AppProjectsProjectIdPaidCampaignsIndexRoute,
  }

const AppProjectsProjectIdPaidRouteWithChildren =
  AppProjectsProjectIdPaidRoute._addFileChildren(
    AppProjectsProjectIdPaidRouteChildren,
  )

interface AppProjectsProjectIdRouteChildren {
  AppProjectsProjectIdPaidRoute: typeof AppProjectsProjectIdPaidRouteWithChildren
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
  AppProjectsProjectIdLandingsLandingIdRoute: typeof AppProjectsProjectIdLandingsLandingIdRoute
  AppProjectsProjectIdOrganizationMembersRoute: typeof AppProjectsProjectIdOrganizationMembersRoute
  AppProjectsProjectIdLandingsIndexRoute: typeof AppProjectsProjectIdLandingsIndexRoute
}

const AppProjectsProjectIdRouteChildren: AppProjectsProjectIdRouteChildren = {
  AppProjectsProjectIdPaidRoute: AppProjectsProjectIdPaidRouteWithChildren,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
  AppProjectsProjectIdLandingsLandingIdRoute:
    AppProjectsProjectIdLandingsLandingIdRoute,
  AppProjectsProjectIdOrganizationMembersRoute:
    AppProjectsProjectIdOrganizationMembersRoute,
  AppProjectsProjectIdLandingsIndexRoute:
    AppProjectsProjectIdLandingsIndexRoute,
}

const AppProjectsProjectIdRouteWithChildren =
  AppProjectsProjectIdRoute._addFileChildren(AppProjectsProjectIdRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppContaRoute: typeof AppContaRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppContaRoute: AppContaRoute,
  AppIndexRoute: AppIndexRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthAcceptInviteRoute: AuthAcceptInviteRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  HooksHealthRoute: HooksHealthRoute,
  HooksMetaAssetFileRoute: HooksMetaAssetFileRoute,
  HooksMetaSyncRoute: HooksMetaSyncRoute,
  LSlugRoute: LSlugRoute,
  HooksAuthGoogleCallbackRoute: HooksAuthGoogleCallbackRoute,
  HooksAuthGoogleStartRoute: HooksAuthGoogleStartRoute,
  HooksGoogleOauthCallbackRoute: HooksGoogleOauthCallbackRoute,
  HooksGoogleOauthStartRoute: HooksGoogleOauthStartRoute,
  HooksHotmartWebhookRoute: HooksHotmartWebhookRoute,
  HooksMetaOauthCallbackRoute: HooksMetaOauthCallbackRoute,
  HooksMetaOauthStartRoute: HooksMetaOauthStartRoute,
  HooksTiktokOauthCallbackRoute: HooksTiktokOauthCallbackRoute,
  HooksTiktokOauthStartRoute: HooksTiktokOauthStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
